export enum ResponseMessage {
  INVALID_ID = "Invalid id",

  ACCOUNT_CREATED = "Successfully Created",
  ACCOUNT_NOT_CREATED = "Account not created",
  PASS_RESET = "Password Reset Successfully",
  INCORRECT_PASSWORD = "Incorrect Password",
  INVALID_CREDENTIALS = "Invalid Credentials",
  UPDATE_FAILED = "Data not updated",
  USER_NOT_FOUND = "User does not exist",
  USER_CREATED_MAIL = "Confirm your email address",
  SUBCRIPTION_EMAIL = "Package Subcribed",
  UN_SUBCRIPTED_PLAN_EMAIL = "Package UnSubcribed",
  SUPPORT_TICKET_MAIL = "Support ticket created",
  USER_UPDATE = "User Updated Successfully",
  USER_BLOCK = "User blocked Successfully",
  USER_ACTIVE = "User activated Successfully",
  FORGOT_MAIL = "Reset Your Password",
  MAIL_ERROR = "Mail Error",
  DETAIL_UPDATE = "Detail Update Successfully",
  ALREADY_USER_EXIST = "This user already exist",
  PHONE_NUMBER_REQUIRED = "Phone number required",
  ALREADY_EXIST_ACTIVITY = "This user already make activity on this project",
  ALREADY_PLAN_EXIST = "This plan already exist",
  ALREADY_BID_EXIST = "This bid already exist",
  ALREADY_SUBMITTED_PROPOSAL = "You have already submitted proposal on this project",
  USER_ALIGNED = "Email already aligned to another role",
  SUCCESSFUL = "Request Successfull",
  REJECT = "Request Unsuccessfull",
  UNOTHORIZED_USER = "Verify from your email and complete your profile",
  MEETING_ALREADY_EXISTS = "Meeting already exists for this time",
  MEETING_CREATED = "Meeting created successfully",
  MEETING_NOT_FOUND = "Meeting not found",
  PASSWORD_NOT_UPDATED = "Password not updated",
  PASSWORD_UPDATED = "Password updated successfully",
  INVALID_OLD_PASSWORD = "Invalid old password",
  PROFILE_PICTURE_UPDATED = "Profile picture updated successfully",
  PROFILE_PICTURE_NOT_UPDATED = "Profile picture not updated",
  ACCOUNT_NOT_FOUND = "Account not found",
  ACCOUNT_DELETED = "Account deleted successfully",
  ACCOUNT_NOT_DELETED = "Account not deleted",
  EMAIL_REQUIRED = "Email required",

  NEWS_LETTER_EMAIL_ALREADY_EXISTS = "Email already subscribed",
  NEWS_LETTER_EMAIL_SUBSCRIBED = "Subscribed successfully",
  NEWS_LETTER_EMAIL_UNSUBSCRIBED = "Unsubscribed successfully",

  CONTACT_MAIL_SENT = "Mail sent successfully",
  CONTACT_MAIL_SUBJECT = "Request Recorded",
  CONTACT_MAIL_ADMIN = "Customer Help Required",
  CONTACT_MAIL_NOT_SENT = "Mail not sent",
  COUNTRIES_NOT_FOUND = "Country not found",
  COUNTRIES_RETRIEVED = "Countries fetched successfully",

  PLAN_NOT_FOUND = "Plan doesn't exist",
  PAYMENT_METHOD_NOT_FOUND = "Payment method doesn't exist",

  NOT_FOUND = "Not Found",
  INVALID_STATUS_VALUE = "invalid status value",
  EXPIRED_PROJECT_BID_ERR_MSG = "this project due date is in past, you cannot update its status now",

  SUBSCRIPTION_NOT_FOUND = "Subscription doesn't exist",
  SUBSCRIPTION_NOT_FOUND_OR_INACTIVE = "Subscription doesn't exist or inactive",
  SUBSCRIPTION_NOT_CANCELLED = "Subscription not cancelled",

  IS_ACTIVE_ARCHIVED_BID = "You can't remove active or archived bid",
  IS_WRONG_ROLE = "You are not authorised for this action",
  OTP_SENT = "OTP sent successfully to your phone number",
  INVALID_OTP = "Invalid OTP",
  OTP_VERIFIED = "Otp verified successfully",
  OTP_EXPIRED = "Otp expired please create new OTP request",
  OTP_SEND_FAILED = "Failed to send OTP",

  // DASHBOARd

  DASHBOARD_USER_LIST = "user list created successfully",
  DASHBOARD_UPDATED = "Dashboard updated successfully",
  DASHBOARD_DELETED = "Dashboard deleted successfully",
  DASHBOARD_STATUS_UPDATED = "Dashboard status updated successfuuly",
  DASHBOARD_NOT_CREATED = "Dashboard not created",
  DASHBOARD_NOT_UPDATED = "Dashboard not updated",
  DASHBOARD_NOT_DELETED = "Dashboard not deleted",
  DASHBOARD_STATUS_NOT_UPDATED = "Dashboard status not updated",
  DASHBOARD_NOT_EXISTS = "Dashboard not exists",
  DASHBOARD_NOT_FOUND = "Dashboard not found",

  BOOK_CREATED = "Book created successfully",
  BOOK_NOT_CREATED = "Book  not created",
  BOOKS_NOT_EXISTS = "Books not exists",
  BOOK_NOT_FOUND = "Book not found",
  BOOK_UPDATED = "Book updated successfully",
  BOOK_NOT_UPDATED = "Book not updated",
  BOOK_NOT_DELETED = "Book not deleted",
  BOOK_DELETED = "Book deleted successfully",
  BOOK_STATUS_UPDATED = "Book status updated successfully",
  BOOK_STATUS_NOT_UPDATED = "Book status not updated",
  BOOK_FAVOURITE_UPDATED = "Book favourite updated successfull",
  BOOK_FAVOURITE_NOT_UPDATED = "Book favourite not updated",

  CLIP_CREATED = "Clip created successfully",
  CLIP_NOT_CREATED = "Clip not created",
  CLIP_NOT_EXISTS = "Clips not exists",
  CLIP_NOT_FOUND = "Clip not found",
  CLIP_UPDATED = "Clip updated successfully",
  CLIP_NOT_UPDATED = "Clip not updated",
  CLIP_DELETED = "Clip deleted successfuully",
  CLIP_NOT_DELETED = "Clip not deleted",
  CLIP_STATUS_UPDATED = "Clip status updated successfully",
  CLIP_STATUS_NOT_UPDATED = "Clip status not updated",
  CLIP_FAVOURITE_UPDATED = "Clip favourite updated successfully",
  CLIP_FAVOURITE_NOT_UPDATED = "Clip favourite not updated",

  BLOG_CREATED = "Blog created successfully",
  BLOG_NOT_CREATED = "Blog not created",
  BLOG_UPDATED = "Blog updated successfully",
  BLOG_NOT_UPDATED = "Blog not updated",
  BLOG_DELETED = "Blog deleted successfully",
  BLOG_NOT_DELETED = "Blog not deleted",
  BLOG_STATUS_UPDATED = "Blog status updated successfully",
  BLOG_FAVOURITE_UPDATED = "Blog favourite updated successfully",
  BLOG_FAVOURITE_NOT_UPDATED = "Blog favourite not updated",
  BLOG_STATUS_NOT_UPDATED = "Blog status not updated",
  BLOG_NOT_FOUND = "Blog not found",
  BLOG_NOT_EXISTS = "Blog not exists",

  PRINT_CREATED = "Print created successfully",
  PRINT_UPDATED = "Print updated successfully",
  PRINT_DELETED = "Print deleted successfully",
  PRINT_STATUS_UPDATED = "Print status updated successfuuly",
  PRINT_NOT_CREATED = "Print not created",
  PRINT_NOT_UPDATED = "Print not updated",
  PRINT_NOT_DELETED = "Print not deleted",
  PRINT_STATUS_NOT_UPDATED = "Print status not updated",
  PRINT_NOT_EXISTS = "Print not exists",
  PRINT_NOT_FOUND = "Print not found",

  WHISTLE_CREATED = "Whistle created successfully",
  WHISTLE_UPDATED = "Whistle updated successfully",
  WHISTLE_DELETED = "Whistle deleted successfully",
  WHISTLE_STATUS_UPDATED = "Whistle status updated successfully",
  WHISTLE_NOT_CREATED = "Whistle not created",
  WHISTLE_NOT_UPDATED = "Whistle not updated",
  WHISTLE_NOT_DELETED = "Whistle not deleted",
  WHISTLE_STATUS_NOT_UPDATED = "Whistle status not updated",
  WHISTLE_NOT_EXISTS = "Whistle not exists",
  WHISTLE_NOT_FOUND = "Whistle not found",

  LIBRARY_CREATED = "Library created successfully",
  LIBRARY_UPDATED = "Library updated successfully",
  LIBRARY_DELETED = "Library deleted successfully",
  LIBRARY_STATUS_UPDATED = "Library status updated successfuuly",
  LIBRARY_NOT_CREATED = "Library not created",
  LIBRARY_NOT_UPDATED = "Library not updated",
  LIBRARY_NOT_DELETED = "Library not deleted",
  LIBRARY_STATUS_NOT_UPDATED = "Library status not updated",
  LIBRARY_NOT_EXISTS = "Library not exists",
  LIBRARY_NOT_FOUND = "Library not found",

  LOUNGE_CREATED = "Lounge created successfully",
  LOUNGE_UPDATED = "Lounge updated successfully",
  LOUNGE_DELETED = "Lounge deleted successfully",
  LOUNGE_STATUS_UPDATED = "Lounge status updated successfuuly",
  LOUNGE_NOT_CREATED = "Lounge not created",
  LOUNGE_NOT_UPDATED = "Lounge not updated",
  LOUNGE_NOT_DELETED = "Lounge not deleted",
  LOUNGE_STATUS_NOT_UPDATED = "Lounge status not updated",
  LOUNGE_NOT_EXISTS = "Lounge not exists",
  LOUNGE_NOT_FOUND = "Lounge not found",
  MESSAGE_NOT_FOUND = "Message not found",
  ACTION_INVALID = "Action type is invalid",
  CREATOR_NOT_REPORT = "Createor can't hide or report",
  LOUNGE_MESSAGE_ALREADY_REACTED = "Lounge message already reacted",
  LOUNGED_MESSAGED_REACTED_SUCCESSFULLY = "Lounge message reacted successfully",

  TAPE_CREATED = "Tape created successfully",
  TAPE_UPDATED = "Tape updated successfully",
  TAPE_DELETED = "Tape deleted successfully",
  TAPE_STATUS_UPDATED = "Tape status updated successfuuly",
  TAPE_NOT_CREATED = "Tape not created",
  TAPE_NOT_UPDATED = "Tape not updated",
  TAPE_NOT_DELETED = "Tape not deleted",
  TAPE_STATUS_NOT_UPDATED = "Tape status not updated",
  TAPE_NOT_EXISTS = "Tape not exists",
  TAPE_NOT_FOUND = "Tape not found",

  PRACTICE_CREATED = "Practice created successfully",
  PRACTICE_UPDATED = "Practice updated successfully",
  PRACTICE_DELETED = "Practice deleted successfully",
  PRACTICE_STATUS_UPDATED = "Practice status updated successfuuly",
  PRACTICE_NOT_CREATED = "Practice not created",
  PRACTICE_NOT_UPDATED = "Practice not updated",
  PRACTICE_NOT_DELETED = "Practice not deleted",
  PRACTICE_STATUS_NOT_UPDATED = "Practice status not updated",
  PRACTICE_NOT_EXISTS = "Practice not exists",
  PRACTICE_NOT_FOUND = "Practice not found",

  FAQ_CREATED = "Faq created successfully",
  FAQ_UPDATED = "Faq updated successfully",
  FAQ_DELETED = "Faq deleted successfully",
  FAQ_STATUS_UPDATED = "Faq status updated successfuuly",
  FAQ_NOT_CREATED = "Faq not created",
  FAQ_NOT_UPDATED = "Faq not updated",
  FAQ_NOT_DELETED = "Faq not deleted",
  FAQ_STATUS_NOT_UPDATED = "Faq status not updated",
  FAQ_NOT_EXISTS = "Faq not exists",
  FAQ_NOT_FOUND = "Faq not found",

  // Plans
  PLAN_CREATED = "Plan created successfully",
  PLAN_UPDATED = "Plan updated successfully",
  PLAN_DELETED = "Plan deleted successfully",
  PLAN_STATUS_UPDATED = "Plan status updated successfuuly",
  PLAN_NOT_CREATED = "Plan not created",
  PLAN_NOT_UPDATED = "Plan not updated",
  PLAN_NOT_DELETED = "Plan not deleted",
  PLAN_STATUS_NOT_UPDATED = "Plan status not updated",
  PLAN_NOT_EXISTS = "Plan not exists",

  // PLAN PROMOTIONS
  PLAN_PROMOTION_ALREADY_EXISTS = "Promotion on this plan already exists",
  PLAN_PROMOTION_CREATED = "Promotion created successfully",
  PLAN_PROMOTION_UPDATED = "Promotion updated successfully",
  PLAN_PROMOTION_DELETED = "Promotion deleted successfully",
  PLAN_PROMOTION_NOT_FOUND = "Promotion not found",

  // PROMO CODE
  PROMO_CODE_CREATED = "Promo code created successfully",
  PROMO_CODE_UPDATED = "Promo code updated successfully",
  PROMO_CODE_DELETED = "Promo code deleted successfully",
  PROMO_CODE_NOT_CREATED = "Promo code not created",
  PROMO_CODE_NOT_UPDATED = "Promo code not updated",
  PROMO_CODE_NOT_DELETED = "Promo code not deleted",
  PROMO_CODE_NOT_FOUND = "Promo code not found",
  PROMO_ALREADY_EXISTS = "Promo code already exists",
  PROMO_CODE_IS_EXPIRED = "Promo code is expired",
  PROMO_CODE_IS_NOT_ACTIVE = "Promo code is not active",
  PROMO_CODE_IS_ACCEPTED = "Promo code is accepted",
  PROMO_CODE_NOT_APPLIED_TO_PLAN = "Promo code is not applied to this plan",

  // BOARDROOM
  BOARDROOM_POLL_ENDED = "Poll has ended and cannot be updated",
  BOARDROOM_MESSAGE_NOT_DELETE = "You didn't create this message, so you can't delete it",
  BOARDROOM_CANT_FOLLOW_SELF = "You can't follow yourself",

  // CAREER

  CAREER_CREATED = "Career created successfully",
  CAREER_UPDATED = "Career updated successfully",
  CAREER_DELETED = "Career deleted successfully",
  CAREER_STATUS_UPDATED = "Career status updated successfuuly",
  CAREER_NOT_CREATED = "Career not created",
  CAREER_NOT_UPDATED = "Career not updated",
  CAREER_NOT_DELETED = "Career not deleted",
  CAREER_STATUS_NOT_UPDATED = "Career status not updated",
  CAREER_NOT_EXISTS = "Career not exists",
  CAREER_NOT_FOUND = "Career not found",
  CAREER_ALREADY_EXIST = "Career with given title already exist",
  CAREER_APPLICATION_SUCCESS = "Application submitted successfully",
  CAREER_APPLICANT_NOT_FOUND = "Applicant not found",
  CAREER_APPLICANT_ALREADY_EXIST = "You have already applied",
  CAREER_ID_INVALID = "The specified career does not exist.",

  // SUPPORT

  SUPPORT_CREATED = "support ticket created successfully",
  SUPPORT_UPDATED = "support ticket updated successfully",
  SUPPORT_DELETED = "support ticket deleted successfully",
  SUPPORT_STATUS_UPDATED = "support ticket status updated successfuuly",
  SUPPORT_NOT_CREATED = "support ticket not created",
  SUPPORT_NOT_UPDATED = "support ticket not updated",
  SUPPORT_NOT_DELETED = "support ticket not deleted",
  SUPPORT_STATUS_NOT_UPDATED = "support ticket status not updated",
  SUPPORT_NOT_EXISTS = "support ticket not exists",
  SUPPORT_NOT_FOUND = "support ticket not found",
  SUPPORT_ALREADY_EXIST = "support ticket with given title already exist",
  APPLICANT_SUPPORT_CREATED = "Applicant created successfully",
  SUPPORT_APPLICANT_NOT_FOUND = "Applicant not found",
  SUPPORT_TICKET_ID_INVALID = "The specified support ticket does not exist.",

  // EVENT

  EVENT_CREATED = "Event created successfully",
  EVENT_UPDATED = "Event updated successfully",
  EVENT_DELETED = "Event deleted successfully",
  EVENT_STATUS_UPDATED = "Event status updated successfuuly",
  EVENT_NOT_CREATED = "Event not created",
  EVENT_NOT_UPDATED = "Event not updated",
  EVENT_NOT_DELETED = "Event not deleted",
  EVENT_STATUS_NOT_UPDATED = "Event status not updated",
  EVENT_NOT_EXISTS = "Event not exists",
  EVENT_NOT_FOUND = "Event not found",
  EVENT_ALREADY_EXIST = "event ticket with given an,me already exist",
  RESERVATION_EVENT_CREATED = "Reservation created successfully",
  EVENT_RESERVATION_NOT_FOUND = "Reservation not found",
  EVENT_TICKET_ID_INVALID = "The specified event id does not exist.",
  RESERVATION_ALREADY_EXIST = "You have already reserved",
  MISSING_SMS_PARAMETERS = "MISSING_SMS_PARAMETERS",
  SMS_SENT_SUCCESSFULLY = "SMS_SENT_SUCCESSFULLY",
  SMS_SEND_FAILURE = "SMS_SEND_FAILURE",
  //Chat GPT Response
  CHATGPT_SUCCESS="RESPONSE IS SUCCESSFUL",
  CHATGPT_FAILURE="ERROR GENERATING RESPONSE",
  LECTURE_UNLOCKED="LECTURE UNLOCKED SUCCESSFULLY",
  HABITCREATED="HABIT BREAKER CREATED SUCCESSFULLY",
  
  // Tranquilty
  TRANQUILITY_CREATED="TRANQUILTY CREATED SUCCESSFULLY",
  TRANQUILTY_UPDATED="TRANQUILITY UPDATED SUCCESSFULLY",
  TRANQUILTY_DELETED="TRANQUILTY DELETED SUCCESSFULLY",
  TRANQUILTY_NOTFOUND="TRANQUILTY NOT FOUND",

  // Personal Chat
  MESSAGE_CREATED="MESSAGE CREATED SUCCESSFULLY",
  MESSAGE_UPDATED="MESSAGE UPDATED SUCCESSFULLY",
  MESSAGE_DELETED="MESSAGE DELETED SUCCESSFULLY",
  MESSAGE_NOTFOUND="MESSAGE NOT FOUND"
}
